In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)  #by position,no labels

[11 22 33]


In [ ]:
s1 = pd.Series([10,20,30], index = ['alice', 'bob', 'charlies'])
s2 = pd.Series([1,2,3,4], index = ['bob', 'charlies', 'alice', 'dave'])
print(s1 + s2)

alice       13.0
bob         21.0
charlies    32.0
dave         NaN
dtype: float64


In [ ]:
name = ['alice', 'bob', 'charlie']
marks = [67,36,81]
print(pd.Series(data=marks))
student = pd.Series(data=marks, index=name, name='marks')
print(student)

0    67
1    36
2    81
dtype: int64
alice      67
bob        36
charlie    81
Name: marks, dtype: int64


In [ ]:
np.random.seed(42)
ages = pd.Series(np.random.randint(18,60,4), index=['alice', 'bob', 'charlies', 'dave'])
print(ages)

alice       56
bob         46
charlies    32
dave        25
dtype: int64


In [14]:
print(pd.Series({'alice': 21, 'bob': 26, 'charlie': 23}))

alice      21
bob        26
charlie    23
dtype: int64


In [15]:
q1 = {'japan': 80, 'china': 450, 'india': 200, 'usa': 250}
q2 = {'brazil': 100, 'china': 500, 'india': 210, 'usa': 260}
sales_q1 = pd.Series(q1, name= 'q1')
sales_q2 = pd.Series(q2, name= 'q2')
print(sales_q1)

japan     80
china    450
india    200
usa      250
Name: q1, dtype: int64


In [17]:
print(sales_q1.loc['japan'])
print(sales_q1.iloc[0])

80
80


In [21]:
print(sales_q1.loc['china':'usa'])
print(sales_q1.iloc[1:3])
print(sales_q1.loc['india': 'usa'])

china    450
india    200
usa      250
Name: q1, dtype: int64
china    450
india    200
Name: q1, dtype: int64
india    200
usa      250
Name: q1, dtype: int64


In [22]:
print(sales_q1.index)
print(sales_q1.values)
print(sales_q1 * 2)
print(sales_q1 / 100)
print(sales_q1[sales_q1 > 150])
print(sales_q1.sum(), sales_q1.mean(), sales_q1.max())
print(sales_q1.idxmax())
print(sales_q1.sort_values(ascending = False))

Index(['japan', 'china', 'india', 'usa'], dtype='object')
[ 80 450 200 250]
japan    160
china    900
india    400
usa      500
Name: q1, dtype: int64
japan    0.8
china    4.5
india    2.0
usa      2.5
Name: q1, dtype: float64
china    450
india    200
usa      250
Name: q1, dtype: int64
980 245.0 450
china
china    450
usa      250
india    200
japan     80
Name: q1, dtype: int64


In [23]:
np.random.seed(101)
scores = np.random.randint(0,101,(4,3))

print(scores)
players = ['virat', 'rohit', 'dhoni']

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [27]:
companies = pd.DataFrame({
    'company': ['tcs', 'infosys', 'wipro'],
    'sales' : [100,200,300],
    'profit' : [20,50,70]
})
print(companies)
print(companies.head())
print(companies.shape)
print(companies.columns)
print(companies.index)
print(companies.dtypes)
companies.info()

   company  sales  profit
0      tcs    100      20
1  infosys    200      50
2    wipro    300      70
   company  sales  profit
0      tcs    100      20
1  infosys    200      50
2    wipro    300      70
(3, 3)
Index(['company', 'sales', 'profit'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
company    object
sales       int64
profit      int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   company  3 non-null      object
 1   sales    3 non-null      int64 
 2   profit   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
