In [1]:
import numpy as np

Q1

Write a NumPy program to get the numpy version and show numpy build configuration.

In [15]:
print(np.__version__)
print(np.__config__)

2.5.3
<module 'numpy.__config__' from 'C:\\Users\\PGCP-AI.STUDENTSDC\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\numpy\\__config__.py'>


Q2

Write a NumPy program to get help on the add function.

In [18]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

Q3

Write a NumPy program to test whether none of the elements of a given array is zero.

In [31]:
arr = np.array([10,11,45,0,9])
print(arr == 0)
print(np.all(arr))

[False False False  True False]
False


Q4

Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [34]:
arr = np.array([10,11,45,0,9])
print(arr != 0)
print(np.all(arr))

[ True  True  True False  True]
False


Q5 

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a
Number).

In [39]:
arr = np.array([np.nan,11,np.inf,0,9])
print(np.isfinite(arr))

[False  True False  True  True]


Q6

Write a NumPy program to test element-wise for positive or negative infinity.

In [40]:
arr = np.array([10,-np.inf,45,0,np.inf])
print(np.isinf(arr))

[False  True False False  True]


Q7

Write a NumPy program to test element-wise for NaN of a given array.

In [98]:
arr = np.array([np.nan,11,np.nan,0,9])
print(np.isnan(arr))

[ True False  True False False]


Q8 

Write a NumPy program to test element-wise for complex number, real number of a given array.
Also test whether a given number is a scalar type or not.

In [96]:
arr = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(arr))
print(np.isreal(arr))
print(np.isscalar(arr))
print(arr)

[ True False False False False  True]
[False  True  True  True  True False]
False
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]


Q9

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.

In [51]:
a1 = np.array([12,23,45,65])
a2 = np.array([67,98,56,34])

print(np.greater(a1,a2))
print(np.greater_equal(a1,a2))
print(np.less(a1,a2))
print(np.less_equal(a1,a2))

[False False False  True]
[False False False  True]
[ True  True  True False]
[ True  True  True False]


Q10

Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of
the memory occupied by the array.

In [56]:
arr = np.array([1,7,13,105])
arr.nbytes

32

Q11 

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [60]:
print(np.zeros(10))
print(np.ones(10))
print(np.full(10,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


Q12

Write a NumPy program to create an array of the integers from 30 to70.

In [61]:
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Q13

Write a NumPy program to create an array of all the even integers from 30 to 70.

In [62]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q14

Write a NumPy program to create a 3x3 identity matrix.

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q15

Write a NumPy program to generate a random number between 0 and 1.

In [151]:
np.random.random()

0.047698769254724716

Q16

Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [78]:
np.random.normal(0,16,15)

array([-6.24023937e+00, -7.00827618e+00, -1.20666356e+01,  1.39120919e+01,
        3.70587596e-01, -1.42994876e+01,  8.36768754e-03, -1.26120374e+00,
        1.24634389e+01, -4.50888757e+00,  1.52019971e+01,  1.28735318e+01,
        7.61712718e-01, -1.46433137e+01, -1.21747282e+01])

Q17

Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [84]:
arr = np.arange(15,56)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Q18 

Write a NumPy program to create a 3X4 array using and iterate over it.

In [92]:
arr = np.random.randint(1,10,(3,4))
print(arr)
for i in np.nditer(arr):
    print(i)

[[1 4 2 1]
 [7 2 8 9]
 [9 2 4 4]]
1
4
2
1
7
2
8
9
9
2
4
4


Q19

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5
and 50.

In [93]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Q20

Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
numbers in the range from 9 to 15.

In [103]:
arr = np.arange(21)
arr[(arr >= 9) & (arr<=15)] *=-1
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

Q21

Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [106]:
 np.random.randint(0,11,5)

array([0, 3, 5, 4, 9], dtype=int32)

Q22

Write a NumPy program to multiply the values of two given vectors.

In [110]:
arr1 = np.array([23,56,85,93,12])
arr2 = np.array([56,89,60,2,0])
arr1 * arr2

array([1288, 4984, 5100,  186,    0])

Q23

Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [117]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Q24

Write a NumPy program to find the number of rows and columns of a given matrix.

In [120]:
arr = np.random.randint(1,22,(3,3))
print('Rows :',arr.shape[0])
print('Columns :',arr.shape[1])

Rows : 3
Columns : 3


Q25

Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [121]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q26

Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
equal to 1, and inside 0.

In [135]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Q27

Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1,
2, 3, 4, 5.

In [142]:
arr = np.zeros((5,5))
np.fill_diagonal(arr,[1,2,3,4,5])
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

Q28

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the
main diagonal.

In [177]:
arr = np.zeros((4,4))
arr[::2,1::2] = 1
arr[1::2,::2] = 1
arr

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Q29

Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [150]:
np.random.random((3,3,3))

array([[[0.65398833, 0.76449865, 0.38720025],
        [0.40398331, 0.76621243, 0.6601882 ],
        [0.70958813, 0.5225559 , 0.20695831]],

       [[0.6878376 , 0.0060776 , 0.94541529],
        [0.3751175 , 0.82895726, 0.29375352],
        [0.95873884, 0.10267332, 0.04014783]],

       [[0.01022587, 0.380847  , 0.79951352],
        [0.54854845, 0.98680446, 0.767475  ],
        [0.08866021, 0.41865132, 0.50210049]]])

Q30

Write a NumPy program to compute sum of all elements, sum of each column and sum of each row
of a given array.

In [158]:
arr = np.random.randint(10,40,(3,3))
print(arr)
print('Sum :', arr.sum())
print('Sum Of Rows :',arr.sum(axis=1))
print('Sum Of Column :',arr.sum(axis=0))

[[28 14 13]
 [18 23 33]
 [38 29 13]]
Sum : 209
Sum Of Rows : [55 74 80]
Sum Of Column : [84 66 59]


Q31

Write a NumPy program to compute the inner product of two given vectors.

In [159]:
arr1 = np.array([4,6,9,14])
arr2 = np.array([7,8,34,97])
np.inner(arr1,arr2)

np.int64(1740)

Q32

Write a NumPy program to add a vector to each row of a given matrix.

In [162]:
arr1 = np.array([3,6,8])
arr2 = np.arange(1,10).reshape(3,3)
arr1+arr2

array([[ 4,  8, 11],
       [ 7, 11, 14],
       [10, 14, 17]])

Q33

Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the
points using matplotlib.