In [1]:
import numpy as np

In [3]:
sales = [0,5,155,0,518,616]
sales_array = np.array(sales)
print(sales_array)

[  0   5 155   0 518 616]


In [4]:
print(sales_array.shape)

(6,)


In [5]:
print(sales_array.size)

6


In [6]:
print(sales_array.dtype)

int64


In [7]:
print(sales_array.ndim)

1


In [8]:
# 2D Array

In [9]:
store_sales = np.array([
    [120,135,150,160],
    [90,110,105,130],
    [200,120,210,220]
])
print(store_sales)

[[120 135 150 160]
 [ 90 110 105 130]
 [200 120 210 220]]


In [11]:
print(store_sales.size)

12


In [12]:
print(store_sales.shape)

(3, 4)


In [13]:
print(store_sales.dtype)

int64


In [14]:
print(store_sales.ndim)

2


In [15]:
# Where 

In [16]:
result_array = np.where(sales_array == 0, 'No Sales','Some Sales')
print(result_array)

['No Sales' 'Some Sales' 'Some Sales' 'No Sales' 'Some Sales' 'Some Sales']


In [17]:
# boolean mask 
bool_mask = sales_array != 0
print(bool_mask)

[False  True  True False  True  True]


In [18]:
print(sales_array[bool_mask])

[  5 155 518 616]
