In [1]:
import numpy as np

In [2]:
virat_runs = np.array([12,24,45,67])
print(virat_runs)

[12 24 45 67]


In [11]:
virat_runs = np.array([12,'24',45,67])
print(virat_runs , virat_runs.dtype)

['12' '24' '45' '67'] <U21


In [10]:
virat_runs = np.array([12,24.445,45,67])
print(virat_runs, virat_runs.dtype)

[12.    24.445 45.    67.   ] float64


In [8]:
team = np.array([
    [12,34,45],
    [23,67,37],
    [45,78,98]
])
print(team)

[[12 34 45]
 [23 67 37]
 [45 78 98]]


In [9]:
player_ages = np.array((23,45,34))
print(player_ages)

[23 45 34]


In [14]:
# specify datatype while creating array
over = np.array([3,6,4], dtype = float)
print(over, over.dtype)

[3. 6. 4.] float64


In [17]:
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
full = np.full((3,3),8)
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [22]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np 
empty = np.empty((3,3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
array = np.arange(1,20)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
array = np.arange(1,20,4)
print(array)

[ 1  5  9 13 17]


In [32]:
# Example -> x-axis and y-axis values specify
array = np.linspace(1,20,4)
print(array)

[ 1.          7.33333333 13.66666667 20.        ]


In [33]:
array = np.linspace(30,50,5)
print(array)

[30. 35. 40. 45. 50.]


In [34]:
array = np.linspace(30,50)
print(array)

[30.         30.40816327 30.81632653 31.2244898  31.63265306 32.04081633
 32.44897959 32.85714286 33.26530612 33.67346939 34.08163265 34.48979592
 34.89795918 35.30612245 35.71428571 36.12244898 36.53061224 36.93877551
 37.34693878 37.75510204 38.16326531 38.57142857 38.97959184 39.3877551
 39.79591837 40.20408163 40.6122449  41.02040816 41.42857143 41.83673469
 42.24489796 42.65306122 43.06122449 43.46938776 43.87755102 44.28571429
 44.69387755 45.10204082 45.51020408 45.91836735 46.32653061 46.73469388
 47.14285714 47.55102041 47.95918367 48.36734694 48.7755102  49.18367347
 49.59183673 50.        ]


In [37]:
print(np.arange(1,2,0.25))

[1.   1.25 1.5  1.75]


In [47]:
random = np.random.randint(20)
print(random)

3


In [48]:
random = np.random.randint(20,40,10)
print(random)

[35 22 32 39 34 30 32 22 36 21]


In [49]:
random = np.random.randint(20,40,(5,5))
print(random)

[[24 30 25 23 28]
 [22 39 23 27 34]
 [22 37 32 25 33]
 [27 34 35 31 24]
 [27 35 38 36 25]]


In [69]:
# Random Numbers  -> every run got different random number
try1  = np.random.randint(0,10,5)
print(try1)

[2 4 7 7 9]


In [89]:
# with seed -> every run you got same random number (value of seed -> any integer but standard 1,42,101)
np.random.seed(42)
try1  = np.random.randint(0,10,5)
print(try1)

[6 3 7 4 6]


In [91]:
# uniform -> provide equal chance to every number within the range to appear as random number (might be non repeative)
strike_rate = np.random.uniform(100,200,10)
print(strike_rate)

[199.22115593 161.74815096 161.16531605 100.70663052 102.3062425
 152.47746603 139.98609717 104.66656632 197.37555188 123.27713404]


In [92]:
batting_avg = np.random.normal(0,100,5)
print(batting_avg)

[ 22.20789016 -76.79765019  14.24646024  -3.46521842 113.43392655]


In [93]:
eco = np.random.randn(2,3)
print(eco)

[[-0.10474555 -0.52512285  1.91277127]
 [-2.02671962  1.11942361  0.77919263]]


In [94]:
win = np.random.rand(5)
print(win)

[0.60999666 0.83319491 0.17336465 0.39106061 0.18223609]


In [101]:
squad = np.array(['vikram', 'viraj', 'aditya', 'nitin'])
print(np.random.choice(squad , 3 , replace=False))

['vikram' 'aditya' 'nitin']


In [102]:
rng = np.random.default_rng(42)
print(rng.integers(1,7,10))

[1 5 4 3 3 6 1 5 2 1]
