In [2]:
import numpy as np
sales = np.random.randint(100,300,15)
print(sales)


[252 150 228 239 181 187 194 191 130 187 203 282 175 229 150]


In [12]:
print("Total :", sales.sum())
print("Mean :", sales.mean())
print("Median :", np.median(sales))
print("Min :", sales.min(), 'Max:' , sales.max())
print("Range :", np.ptp(sales))
print("Var :", sales.var().round(2))
print("Std :", sales.std().round(2))
q1,q2,q3 = np.percentile(sales,[25,50,75])
print("Q1 Q2 Q3 :",q1,q2,q3,"IQR :",q3-q1)

Total : 2978
Mean : 198.53333333333333
Median : 191.0
Min : 130 Max: 282
Range : 152
Var : 1592.78
Std : 39.91
Q1 Q2 Q3 : 178.0 191.0 228.5 IQR : 50.5


In [6]:
# With Specific Axis
store_sales = np.random.randint(100,300,(3,4))
print(store_sales)

[[193 136 124 292]
 [212 209 144 111]
 [281 181 172 281]]


In [7]:
print(store_sales.sum())#sums everything
print(store_sales.sum(axis=0))#rows sum
print(store_sales.sum(axis=1))#col sum

2336
[686 526 440 684]
[745 676 915]
