In [4]:
import numpy as np
np.random.seed(1)
marks = np.random.randint(30,101,10)
print(marks)

[67 42 39 35 94 46 31 36 55 80]


In [5]:
print(marks[8])

55


In [6]:
print(marks[-1])

80


In [7]:
print(marks[1:5])

[42 39 35 94]


In [8]:
print(marks[:3])

[67 42 39]


In [9]:
print(marks[-3:])

[36 55 80]


In [10]:
print(marks[::2])

[67 39 94 31 55]


In [11]:
print(marks[::-1])

[80 55 36 31 46 94 35 39 42 67]


In [12]:
# Assign one value to whole slice

In [13]:
marks[0:3] = 75
print(marks)

[75 75 75 35 94 46 31 36 55 80]


In [14]:
# Shallow Copy

In [15]:
top_batch = marks[0:5]
top_batch[:] = 99
print(top_batch) #original change
print(marks)

[99 99 99 99 99]
[99 99 99 99 99 46 31 36 55 80]


In [16]:
# Deep Copy

In [17]:
marks_copy = marks.copy()
marks_copy[:] = 99
print(marks_copy) #original unchanged
print(marks)

[99 99 99 99 99 99 99 99 99 99]
[99 99 99 99 99 46 31 36 55 80]


In [ ]:
#conitional (boolean) selection

In [18]:
marks = np.array([23,45,65,76,87,25])
passed = marks >=35
print(passed)
print(marks[passed])
print(marks[marks > 70])

[False  True  True  True  True False]
[45 65 76 87]
[76 87]


#multiple condition: use & , | , ~ wityh brackets around each condition

In [19]:
print(marks[ (marks >= 50) & (marks < 80)])
print(marks[ (marks < 35) & (marks > 90)])
print(marks[~passed])
print(np.sum(marks < 35))

[65 76]
[]
[23 25]
2
