In [1]:
import numpy as np

In [2]:
marks = np.array([78,95,88,67,91])
names = np.array(['Amit','Neha','Raj','Priya','Kiran'])

In [3]:
print(np.sort(marks))  # ascending by default

[67 78 88 91 95]


In [4]:
print(np.sort(marks)[::-1])  # descending by reverse ascending

[95 91 88 78 67]


In [9]:
order = np.argsort(-marks)  # -ve -> for descending
print(order)
print(names[order])
print(marks[order])

[1 4 2 0 3]
['Neha' 'Kiran' 'Raj' 'Amit' 'Priya']
[95 91 88 78 67]


In [8]:
order = np.argsort(marks)  # +ve -> for ascending
print(order)
print(names[order])
print(marks[order])

[3 0 2 4 1]
['Priya' 'Amit' 'Raj' 'Kiran' 'Neha']
[67 78 88 91 95]


In [22]:
# Unique

In [23]:
payment_modes = np.array(['UPI', 'Card', 'UPI', 'Cash','Card','UPI','Cash'])
print(np.unique(payment_modes))

['Card' 'Cash' 'UPI']


In [24]:
expenses = np.array([2500,3200,np.nan,4100,3900,np.nan,3000])
print(expenses)

[2500. 3200.   nan 4100. 3900.   nan 3000.]


In [25]:
print(expenses.sum())
print(expenses.mean())

nan
nan


In [26]:
print(np.nan == np.nan) # -> nan is not equal to anything, not even to itself

False


In [27]:
# finding missing values

In [28]:
missing = np.isnan(expenses)
print(missing)

[False False  True False False  True False]


In [29]:
print('Missing Count :',missing.sum())

Missing Count : 2


In [30]:
# Drop : keep only non-missing values
clean = expenses[~np.isnan(expenses)]
print(clean)

[2500. 3200. 4100. 3900. 3000.]


In [31]:
# Filled With Fixed Value
print(np.nan_to_num(expenses,nan=0))

[2500. 3200.    0. 4100. 3900.    0. 3000.]


In [32]:
# Filled With the mean (mean imputation)
filled = np.where(np.isnan(expenses),np.nanmean(expenses),expenses)
print(filled.round(2))

[2500. 3200. 3340. 4100. 3900. 3340. 3000.]
